In [62]:
from dataclasses import dataclass, asdict
import types
@dataclass
class Config:
    learning_rate: float = 0.001
    batch_size: int = 128
    optimizer: str = "adam"

cfg = Config()
print(cfg.learning_rate)  # Output: 0.001
print(cfg.batch_size)     # Output: 128
print(cfg.optimizer)      # Output: 'adam'

cfg_dict = asdict(cfg)  # Convert the dataclass to a dictionary

print(cfg_dict)
# Output: {'learning_rate': 0.001, 'batch_size': 128, 'optimizer': 'adam'}
# print(cfg_dict["learning_rate"])  # Output: 0.001
# print(cfg_dict["batch_size"])     # Output: 128
# print(cfg_dict["optimizer"])      # Output: 'adam'

args = types.SimpleNamespace(**cfg_dict)  # Convert dictionary to an object

print(args.learning_rate)  # Output: 0.001
print(args.batch_size)     # Output: 128
print(args.optimizer)      # Output: 'adam'


0.001
128
adam
{'learning_rate': 0.001, 'batch_size': 128, 'optimizer': 'adam'}
0.001
128
adam


In [61]:
import argparse

def main(args):
    print(f"Training for {args.epochs} epochs with batch size {args.batch_size}")

if __name__ == "__main__":
    # Step 1: Create an ArgumentParser
    parser = argparse.ArgumentParser(description="Training script")
    
    # Step 2: Add arguments
    parser.add_argument('--epochs', type=int, default=10, help="Number of training epochs")
    parser.add_argument('--batch_size', type=int, default=32, help="Batch size for training")


    # args = parser.parse_args()
    args, unknown = parser.parse_known_args()##because using jupyter

    # Step 4: Pass parsed arguments to the main function
    main(args)


Training for 10 epochs with batch size 32


In [60]:
import argparse

def main(args):
    print(f"Training for {args['epochs']} epochs with batch size {args['batch_size']}")

if __name__ == "__main__":
    # Step 1: Create an ArgumentParser
    parser = argparse.ArgumentParser(description="Training script")
    
    # Step 2: Add arguments
    parser.add_argument('--epochs', type=int, default=10, help="Number of training epochs")
    parser.add_argument('--batch_size', type=int, default=32, help="Batch size for training")

    # Step 3: Parse arguments and convert to dictionary
    args, unknown = parser.parse_known_args()
    
    args = vars(args)  # Convert Namespace to a dictionary

    # Step 4: Pass parsed arguments to the main function
    main(args)


Training for 10 epochs with batch size 32


In [7]:
dataset = {
    "observations": [1, 2, 3],
    "actions": [0.1, 0.2, 0.3],
    "rewards": [1, -1, 2]
}

for k, v in dataset.items():
    print(f"Key: {k}, Value: {v}")


Key: observations, Value: [1, 2, 3]
Key: actions, Value: [0.1, 0.2, 0.3]
Key: rewards, Value: [1, -1, 2]


In [26]:
import numpy as np

# Example dataset
dataset = {
    "cost_returns": np.array([1.5, 3.0, 4.5, 2.0, 5.0, 0.5]),  # Example cost returns
    "actions": np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])       # Example actions
}

# Example cost limit
cost_limit = 2.0

# Initialize selected_transition as a binary array (e.g., all zeros initially)
selected_transition = np.zeros_like(dataset["cost_returns"])

# Apply the condition to set values to 1 where cost returns >= 2 * cost_limit
selected_transition[dataset["cost_returns"] >= 2 * cost_limit] = 1
print("selcted transitions", selected_transition)
# Now, filter dataset values based on selected_transition
for k, v in dataset.items():
    dataset[k] = v[selected_transition == 1]

# Print the updated dataset
print("Filtered Dataset:")
print(dataset)


selcted transitions [0. 0. 1. 0. 1. 0.]
Filtered Dataset:
{'cost_returns': array([4.5, 5. ]), 'actions': array([0.3, 0.5])}


In [25]:
import numpy as np

# Example dataset
dataset = {
    "cost_returns": np.array([1.5, 3.0, 4.5, 2.0, 5.0, 0.5]),  # Example cost returns
    "actions": np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])       # Example actions
}

# Example cost limit
cost_limit = 2.0

# Initialize selected_transition as a binary array (e.g., all zeros initially)
# selected_transition = np.zeros_like(dataset["cost_returns"])

# Apply the condition to set values to 1 where cost returns >= 2 * cost_limit
selected_transition = dataset["cost_returns"] >= 2 * cost_limit
print("selcted transitions", selected_transition)
# Now, filter dataset values based on selected_transition
for k, v in dataset.items():
    dataset[k] = v[selected_transition]

# Print the updated dataset
print("Filtered Dataset:")
print(dataset)


selcted transitions [False False  True False  True False]
Filtered Dataset:
{'cost_returns': array([4.5, 5. ]), 'actions': array([0.3, 0.5])}


In [24]:
import pyrallis

# Define a class or function to be wrapped
@pyrallis.wrap()
class MyConfig:
    batch_size: int
    learning_rate: float
    epochs: int

# Function that uses the class wrapped by pyrallis
def train_model(config: MyConfig):
    print(f"Batch Size: {config.batch_size}")
    print(f"Learning Rate: {config.learning_rate}")
    print(f"Epochs: {config.epochs}")

# Command to run the script
# python script.py --batch_size 32 --learning_rate 0.001 --epochs 10


In [33]:
import torch
import torch.distributions as dist

# Let's say our action space is 2D (e.g., [x, y])
# Create a 2D Normal distribution (mean=0, std=1) for each action component
mu = torch.zeros(2)  # Mean of the distribution (2D)
sigma = torch.ones(2)  # Standard deviation of the distribution (2D)
pi = dist.Normal(mu, sigma)  # Define the distribution

# Now, let's define a specific action [x, y]
act = torch.tensor([1.0, -1.0])  # Example action

# Compute the log probability of this action
log_prob = pi.log_prob(act)  # This returns log probabilities for each dimension of the action

print("Log probabilities for each component of the action:")
print(log_prob)  # It will show the log probabilities for each dimension of the action

# Sum the log probabilities (this is often done when dealing with multivariate distributions)
log_prob_sum = log_prob.sum()  # Sum along the last axis (for this 1D tensor, it's just the sum of the two components)
print("\nSum of log probabilities:")
print(log_prob_sum)  # This gives us a single scalar log probability value
# log(p(a)*p(b)) = log(p(a))+log(p(B)) 


Log probabilities for each component of the action:
tensor([-1.4189, -1.4189])

Sum of log probabilities:
tensor(-2.8379)


In [36]:
my_range = range(5)
print(my_range)
my_list = list(my_range)
print(my_list)  # Output: [0, 1, 2, 3, 4]


range(0, 5)
[0, 1, 2, 3, 4]


In [9]:
import torch
x = torch.tensor([[1], [2], [3]])  # Shape: (3, 1)
print(x)
x_expanded = x.expand(3, 1)
x_repeated = x.repeat(1, 4)

print(x_expanded)  # Memory-efficient, just changes view
print(x_repeated)  # Actually copies data


tensor([[1],
        [2],
        [3]])
tensor([[1],
        [2],
        [3]])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])


In [10]:
A = torch.randn(2, 3, 4)  # Shape (batch=2, 3, 4)
B = torch.randn(2, 4, 5)  # Shape (batch=2, 4, 5)

C = torch.bmm(A, B)  # (batch=2, 3, 5)
print(C.shape)  # Output: torch.Size([2, 3, 5])


torch.Size([2, 3, 5])


In [13]:
import torch
import matplotlib.pyplot as plt

# Set random seed for reproducibility
torch.manual_seed(42)

# Define dimensions
batch_size = 2
state_dim = 3
num_action = 4

# Create random tensors
g = torch.rand(batch_size, state_dim, num_action)
action = torch.rand(batch_size, num_action)

# Perform both einsum operations
gu_original = torch.einsum('bsa,ba->bs', g, action)
gu_new = torch.einsum('bas,ba->bs', g.permute(0, 2, 1), action)

# Print shapes and values
print("Original einsum shape:", gu_original.shape)
print("New einsum shape:", gu_new.shape)
print("\nOriginal einsum result:\n", gu_original)
print("\nNew einsum result:\n", gu_new)



Original einsum shape: torch.Size([2, 3])
New einsum shape: torch.Size([2, 3])

Original einsum result:
 tensor([[0.6681, 0.4533, 0.5887],
        [1.2167, 0.7889, 0.4954]])

New einsum result:
 tensor([[0.6681, 0.4533, 0.5887],
        [1.2167, 0.7889, 0.4954]])


In [16]:
import torch

# Set random seed for reproducibility
torch.manual_seed(42)

# Define dimensions
a, b, c, d, e = 2, 3, 4, 5, 6

# Create random tensors
x = torch.rand(a, b, c, d, e)
y = torch.rand(a, c, e)

# Original einsum
result1 = torch.einsum('abcde,ace->abd', x, y)

# Flipped order einsum
result2 = torch.einsum('aedcb,ace->abd', x.permute(0, 4, 3, 2, 1), y)

print("Result 1 shape:", result1.shape)
print("Result 2 shape:", result2.shape)

print("\nResult 1 (first few elements):")
print(result1[:, :, 0])

print("\nResult 2 (first few elements):")
print(result2[:, :, 0])

print("\nAre results equal?", torch.allclose(result1, result2, atol=1e-6))


Result 1 shape: torch.Size([2, 3, 5])
Result 2 shape: torch.Size([2, 3, 5])

Result 1 (first few elements):
tensor([[7.1426, 6.6532, 5.6248],
        [5.4513, 4.2430, 5.0380]])

Result 2 (first few elements):
tensor([[7.1426, 6.6532, 5.6248],
        [5.4513, 4.2430, 5.0380]])

Are results equal? True


In [18]:
print(3*[1])

[1, 1, 1]


In [45]:
class MyClass:
    def __init__(self, param1=0, param2=0, param3=0, param4=0, **kwargs):
        # Regular parameters
        self.param1 = param1
        self.param2 = param2
        
        # Default parameters
        self.param3 = param3
        self.param4 = param4
        print(kwargs)

        
    def show_params(self):
        print(f"param1: {self.param1}")
        print(f"param2: {self.param2}")
        print(f"param3: {self.param3}")
        print(f"param4: {self.param4}")

# Now, let's create a dictionary of parameters (args) and pass them to the class.
args = {
    "param1": 5, 
    "param2": 10, 
    "param3": 50,  # This overrides the default value for param3
    "param4": 100, # This overrides the default value for param4
    "extra_param1": 500,  # Extra parameter not defined in __init__()
    "extra_param2": 1000  # Another extra parameter
}

# Unpack the args dictionary and pass them to MyClass
obj = MyClass(**args)

# Call the show_params method to see the parameters
obj.show_params()


{}
param1: {'param1': 5, 'param2': 10, 'param3': 50, 'param4': 100, 'extra_param1': 500, 'extra_param2': 1000}
param2: 0
param3: 0
param4: 0


In [39]:
def example_function(param1, param2, param3=30):
    print(f"param1: {param1}")
    print(f"param2: {param2}")
    print(f"param3: {param3}")

# Dictionary with arguments
args = {
    "param1": 5, 
    "param2": 10, 
    "param3": 50  # This overrides the default value for param3
}

# Unpack the dictionary and pass as keyword arguments
example_function(**args)


param1: 5
param2: 10
param3: 50
